### ISSUE TITLE
제안발표 질의응답 사항

### ISSUE THREAD

**Issue by MinSungJe** [CSID-DGU/2024-1-OSSProj-GiveMeTen-11#12]
## 내용
동국패스 내 공지사항 알림 기능과의 구체적인 차별점이 무엇인지?

**Comment by IAMBH** [comment]
### 동국패스와의 차별점
1. 학생이 속한 학과별 공지사항을 받을 수 있음
   - 동국패스는 학과별 공지사항에 대한 정보를 제공하지 않음
  
2. 공지사항에 대한 카테고리를 세부적으로 나누어 필요로하는 정보만 받을 수 있도록 함
   - 동국패스의 경우 크게 "학사공지" 으로만 되어있음 
   - 불필요한 알림을 줄이는 효과
<img width="1366" alt="스크린샷 2024-04-22 오후 5 58 40" src="https://github.com/CSID-DGU/2024-1-OSSProj-GiveMeTen-11/assets/127372538/3139e817-a98f-4b3e-881b-df2f15fbbd0c">

3. 카카오톡 알림 기능 제공
    - 학생들의 동국패스 사용빈도가 떨어지기 때문에  자주 사용하고 접근성이 좋은 카카오톡으로 알림을 주는 것이 나을 것으로 판단

4. 학사일정에 대한 정보 제공 및 알림을 통해 학생들의 인지를 도움
    - 동국패스는 학사일정에 대한 정보를 제공하지 않음

**Comment by MinSungJe** [comment]
교수님 컨펌 결과 해당 내용을 중간보고서의 사례조사 부분에 동국패스와의 비교점 부분으로 넣으면 될 거 같습니다.
