### ISSUE TITLE
[제안발표 검토의견] 문단 형식으로 기술

### ISSUE THREAD

**Issue by MinSungJe** [CSID-DGU/2024-1-OSSProj-GiveMeTen-11#14]
## 현재
- 문단 형식으로 기술
## 개선점
- 개요, 배경, 필요성 등 기술요소별로 항목을 분리 기술
- 다른 부분도 전반적으로 개선
- 발표자료의 정제된 내용을 반영

**Comment by pjh0428** [comment]
기술요소별로 분리하여 기술하였고 내용을 정제하여 가독성을 향상시켰습니다.
