### ISSUE TITLE
[제안발표 검토의견] 비교 대상을 설명만 함

### ISSUE THREAD

**Issue by MinSungJe** [CSID-DGU/2024-1-OSSProj-GiveMeTen-11#15]
## 현재
- 비교 대상을 설명만 함
## 개선점
- 표형식을 도입 비교항목과 내용을 기술
- 팀제안 우수성 제시

**Comment by pjh0428** [comment]
비교 테이블 제작 및 도입하였고 우수성에 대하여 추가로 기술하였습니다.
