### ISSUE TITLE
[제안발표 검토의견] 블록 다이어그램 제시

### ISSUE THREAD

**Issue by MinSungJe** [CSID-DGU/2024-1-OSSProj-GiveMeTen-11#16]
## 현재
- 블록 다이어그램 제시
## 개선점
- 유스캐이스, 시퀀스다이어그램 보강

**Comment by MinSungJe** [comment]
유스케이스 다이어그램 제작한 거 올리겠습니다!

![image](https://github.com/CSID-DGU/2024-1-OSSProj-GiveMeTen-11/assets/101497652/8c497469-a09b-4723-a9cd-0a7d11ad97fd)

**Comment by MinSungJe** [comment]
2024-05-01자로 수정사항 있어 수정했습니다.
![image](https://github.com/CSID-DGU/2024-1-OSSProj-GiveMeTen-11/assets/101497652/3521c323-20a2-454c-808b-2f510e798fe6)

**Comment by IAMBH** [comment]
시퀀스 다이어그램 
- 회원가입
![_로그인시퀀스 (1)](https://github.com/CSID-DGU/2024-1-OSSProj-GiveMeTen-11/assets/127372538/30f3bf27-1569-4486-98b1-13f6ba79d11c)
- 공지사항 관리
![_로그인시퀀스 (2)](https://github.com/CSID-DGU/2024-1-OSSProj-GiveMeTen-11/assets/127372538/30364f34-4f06-43ec-9d35-51496e06865e)
