### ISSUE TITLE
[제안발표 검토의견] 2개의 대안을 도출/설명

### ISSUE THREAD

**Issue by MinSungJe** [CSID-DGU/2024-1-OSSProj-GiveMeTen-11#17]
## 현재
- 2개의 대안을 도출/설명
## 개선점
- 표로 요구사항 제시 후 각 대안이 충족하는 모습 제시 후 선택

**Comment by IAMBH** [comment]
1. 표를 통해 요구사항 제시
2. 각 대안 별 설명 및 결과 제시
3. 서비스 개발 방식 비교 부분 추가
![image](https://github.com/CSID-DGU/2024-1-OSSProj-GiveMeTen-11/assets/127372538/3d0e7c45-5de6-44a6-af71-93e6bfbbf113)
