### ISSUE TITLE
[feat] BE API 구현

### ISSUE THREAD

**Issue by IAMBH** [CSID-DGU/2024-1-OSSProj-GiveMeTen-11#21]
## DB 구현
- [x] 회원
- [x] 카테고리

## 기능
- [x] 회원 관리
  - [x] 회원가입
  - [x] 로그인 
  - [x] 로그아웃
- [ ] 공지사항
  - [ ] kakao API
  - [ ] 공지사항 정보 전달

**Comment by MinSungJe** [comment]
kakao API 대신 메세지를 이용해 구현하는 것으로 변경되었습니다.
이후 issue는 #37 참고 바랍니다.
